### ISSUE TITLE
Assimilate other FT repositories into the keen-proxy collective

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/keen-proxy#3]
Essentially, just need to change https://api.keen.io/* to https://keen-proxy.ft.com/*

1. Consider each of the following uses by FT of the keen.io API; 
2. Decide whether or not to update it to utilise keen-proxy.
3. For those that should be updated, consider using next config-vars.

Email
- [x] https://github.com/Financial-Times/anon-email-svc/blob/master/anon-email-svc-lambda/src/main/resources/config.json
- [x] https://github.com/Financial-Times/anon-email-cont/blob/master/anon-email-cont-dw/src/main/resources/config.yaml
- [x] https://github.com/Financial-Times/email-manual-editor/blob/master/src/app/config/config.js

Health check
- [x] https://github.com/Financial-Times/next-health/blob/master/src/server/checks/beacon.check.js

Keen query
- [x] https://github.com/Financial-Times/keen-query/blob/master/lib/aggregator/funnel.js
- [x] https://github.com/Financial-Times/keen-query/blob/master/lib/keen-query/index.js

???
- [x] https://github.com/Financial-Times/next-keen-extraction-scripts/blob/master/stats-on-days.js

Config vars
- [ ] https://github.com/Financial-Times/next-config-vars/blob/master/models/production.js
- Also see: https://github.com/Financial-Times/next-config-vars/issues/135

**Comment by mclarke47** [comment]
https://github.com/Financial-Times/anon-email-svc/blob/master/anon-email-svc-lambda/src/main/resources/config.json
This is a bit misleading, the real config lives in S3 and I forgot to remove keen from this file. anon-email-svc no longer calls keen. That happens in anon-email-cont now for light signup.

https://github.com/Financial-Times/anon-email-cont/blob/master/anon-email-cont-dw/src/main/resources/config.yaml
This is used and calls keen twice every 30 mins (will go down to once in the next couple of days).

**Comment by adambraimbridge** [comment]
Closing this issue, as the rest of the work is covered in Financial-Times/next-config-vars#135
